### ISSUE TITLE
EasyPaisa and Jazz Cash not working

### ISSUE THREAD

**Issue by rafsanopi** [arshmancodes/paymob_pakistan#3]
With card payment, it's working fine I am getting responses in my Paymob account Success.

But for EasyPaisa and Jaaz Cash, It's not working I am getting responses in the Paymob account Declined

![Screenshot_1701584055](https://github.com/arshmancodes/paymob_pakistan/assets/45880457/9fc507d5-1655-4a23-84aa-e0ed5adf38b8)
![Screenshot_1701584155](https://github.com/arshmancodes/paymob_pakistan/assets/45880457/6712b286-8af3-438c-b5b4-79cc9c9ae3a4)

Didn't get any requests in both my apps

**Comment by arshmancodes** [comment]
Can you please share the code where you are trying to process the EasyPaisa and JazzCash payment?

**Comment by rafsanopi** [comment]
Do I need to be in live mode to do payment in EasyPaisa and JazzCash

I am in testing mode

**Comment by arshmancodes** [comment]
Ofcourse, you need to be in live mode, Jazzcash and Easypaisa does not provide Integration ID's for testing.
