### ISSUE TITLE
Easypaisa not working

### ISSUE THREAD

**Issue by rafsanopi** [arshmancodes/paymob_pakistan#5]
Easypaisa not working in live mode 
I Give amountInCents: 2000
Still not getting any response

As for the JazzCash
It reduces user cash without them approving it.
Later on, they just refunded the money

**Comment by arshmancodes** [comment]
You need to provide Mobile Number and email too in order to process the EasyPaisa payment.

**Comment by rafsanopi** [comment]
![Screenshot_20231230_101718](https://github.com/arshmancodes/paymob_pakistan/assets/45880457/ccadfa16-facd-4a35-a661-1967b573c0b9)

But where is the email option??

**Comment by arshmancodes** [comment]
You have to provide the email address in the Coding where you are processing the transaction.
You have to provide the User's Email address, Because the Easypaisa sends a Receipt to the Email.

**Comment by rafsanopi** [comment]
billingData: PaymobBillingData(
                        email: "test@test.com",
                        firstName: "Arshman",
                        lastName: "Afzal",
                        phoneNumber: "+921234567890",
                        apartment: "NA",
                        building: "NA",
                        city: "NA",
                        country: "Pakistan",
                        floor: "NA",
                        postalCode: "NA",
                        shippingMethod: "Online",
                        state: "NA",
                        street: "NA"),
                        
                        Like this way???

**Comment by arshmancodes** [comment]
> billingData: PaymobBillingData( email: "[test@test.com](mailto:test@test.com)", firstName: "Arshman", lastName: "Afzal", phoneNumber: "+921234567890", apartment: "NA", building: "NA", city: "NA", country: "Pakistan", floor: "NA", postalCode: "NA", shippingMethod: "Online", state: "NA", street: "NA"),
> 
> ```
>                     Like this way???
> ```

Yes, but the email should be valid and the Phone number should also be valid, Phone number is optional.

**Comment by rafsanopi** [comment]
What About JazzCash??

Why it's reducing user cash without users approving it then refund

**Comment by arshmancodes** [comment]
When user's enter the MPIN then the amount is deducted from their account and it's on Jazzcash side we can not do anything about it before proceeding to a transaction Jazzcash holds the amount from the User's account and if the transaction fails due to some reason then the amount is refunded to the user's wallet otherwise the amount is paid to the merchant.

**Comment by rafsanopi** [comment]
I have a dedicated backed team
what if My backed team handle all the API from backed 
will i get the same result??

**Comment by arshmancodes** [comment]
@rafsanopi The paymob payment Plugin is basically not dependent on your Backend server all the requests are being sent on the Paymob's server.

The iframe which is being displayed is also on the Paymob's Server.
You can check the Paymob implementation on the Paymob's website then you can get an idea how this is actually working.

I made this plugin to provide ease for the people that can't just totally implement the Payment Gateway from scratch and want simple plugin to just add and start accepting payments.

**Comment by arshmancodes** [comment]
If you still face any issues and want more help from me just let me know we can have a meeting and i can explain all the stuff to you. That may clear all the queries on your side.

Regards,
Arshman Afzal

**Comment by rafsanopi** [comment]
Thanks a lot for your time
It helped very much

**Comment by arshmancodes** [comment]
You're most welcome.

**Comment by rafsanopi** [comment]
Can we join for a meeting? 
Actually My client is from Pakistan and insist to use the Backed to make the payment done. Can we go for a meeting to understand the whole process

**Comment by arshmancodes** [comment]
@rafsanopi  Sure, let me know, You can contact me on LinkedIn, Profile url is in my Github bio.
